{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.1",
      "fix_state": "Not affected",
      "package_name": "python-django20",
      "cpe": "cpe:/a:redhat:openstack:16.1"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.2",
      "fix_state": "Not affected",
      "package_name": "python-django20",
      "cpe": "cpe:/a:redhat:openstack:16.2"
    },
    {
      "product_name": "Red Hat OpenStack Platform 17.1",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack:17.1"
    },
    {
      "product_name": "Red Hat OpenStack Platform 18.0",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:openstack:18.0"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:satellite:6"
    },
    {
      "product_name": "Red Hat Storage 3",
      "fix_state": "Will not fix",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:storage:3"
    },
    {
      "product_name": "Red Hat Update Infrastructure 4 for Cloud Providers",
      "fix_state": "Not affected",
      "package_name": "python-django",
      "cpe": "cpe:/a:redhat:rhui:4::el8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-11-01T07:00:00Z",
  "bugzilla": {
    "description": "python-django: Potential denial of service vulnerability in UsernameField on Windows",
    "id": "2247097",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2247097"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-20",
  "statement": "Only Windows environments are impacted by this vulnerability.",
  "acknowledgement": "",
  "name": "CVE-2023-46695",
  "document_distribution": "",
  "details": [
    "An issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and 4.2 before 4.2.7. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.forms.UsernameField is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.",
    "A vulnerability was discovered in the Django package, where NFKC normalization could take a significant time. This flaw allows a remote, unauthenticated attacker to cause a denial of service by submitting inputs with a large number of Unicode characters."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-46695\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-46695"
  ]
}