{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2025-05-02T00:00:00Z",
  "bugzilla": {
    "description": "kernel: tcp: tcp_make_synack() can be called from process context",
    "id": "2363691",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2363691"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-53121",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\ntcp: tcp_make_synack() can be called from process context\ntcp_rtx_synack() now could be called in process context as explained in\n0a375c822497 (\"tcp: tcp_rtx_synack() can be called from process\ncontext\").\ntcp_rtx_synack() might call tcp_make_synack(), which will touch per-CPU\nvariables with preemption enabled. This causes the following BUG:\nBUG: using __this_cpu_add() in preemptible [00000000] code: ThriftIO1/5464\ncaller is tcp_make_synack+0x841/0xac0\nCall Trace:\n\u003cTASK\u003e\ndump_stack_lvl+0x10d/0x1a0\ncheck_preemption_disabled+0x104/0x110\ntcp_make_synack+0x841/0xac0\ntcp_v6_send_synack+0x5c/0x450\ntcp_rtx_synack+0xeb/0x1f0\ninet_rtx_syn_ack+0x34/0x60\ntcp_check_req+0x3af/0x9e0\ntcp_rcv_state_process+0x59b/0x2030\ntcp_v6_do_rcv+0x5f5/0x700\nrelease_sock+0x3a/0xf0\ntcp_sendmsg+0x33/0x40\n____sys_sendmsg+0x2f2/0x490\n__sys_sendmsg+0x184/0x230\ndo_syscall_64+0x3d/0x90\nAvoid calling __TCP_INC_STATS() with will touch per-cpu variables. Use\nTCP_INC_STATS() which is safe to be called from context switch."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-53121\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-53121\nhttps://lore.kernel.org/linux-cve-announce/2025050231-CVE-2023-53121-40ec@gregkh/T"
  ]
}