{
  "mitigation": "Currently, no mitigation was found for this vulnerability.",
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 9.0 Update Services for SAP Solutions",
      "release_date": "2025-05-05T00:00:00Z",
      "advisory": "RHSA-2025:4439",
      "package": "libsoup-0:2.72.0-8.el9_0.4",
      "cpe": "cpe:/a:redhat:rhel_e4s:9.0"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9.4 Extended Update Support",
      "release_date": "2025-05-05T00:00:00Z",
      "advisory": "RHSA-2025:4440",
      "package": "libsoup-0:2.72.0-8.el9_4.4",
      "cpe": "cpe:/a:redhat:rhel_eus:9.4"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "libsoup",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "libsoup",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "libsoup",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Affected",
      "package_name": "libsoup",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Important",
  "public_date": "2025-04-14T00:00:00Z",
  "bugzilla": {
    "description": "libsoup: Out of bounds reads in soup_headers_parse_request()",
    "id": "2359341",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2359341"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-125",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2025-32906",
  "document_distribution": "",
  "details": [
    "A flaw was found in libsoup, where the soup_headers_parse_request() function may be vulnerable to an out-of-bound read. This flaw allows a malicious user to use a specially crafted HTTP request to crash the HTTP server.",
    "A flaw was found in libsoup, where the soup_headers_parse_request() function may be vulnerable to an out-of-bound read. This flaw allows a malicious user to use a specially crafted HTTP request to crash the HTTP server."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2025-32906\nhttps://nvd.nist.gov/vuln/detail/CVE-2025-32906"
  ]
}