{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Fix deferred",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2025-05-01T00:00:00Z",
  "bugzilla": {
    "description": "kernel: x86/tdx: Panic on bad configs that #VE on \"private\" memory access",
    "id": "2363444",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2363444"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2022-49886",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nx86/tdx: Panic on bad configs that #VE on \"private\" memory access\nAll normal kernel memory is \"TDX private memory\".  This includes\neverything from kernel stacks to kernel text.  Handling\nexceptions on arbitrary accesses to kernel memory is essentially\nimpossible because they can happen in horribly nasty places like\nkernel entry/exit.  But, TDX hardware can theoretically _deliver_\na virtualization exception (#VE) on any access to private memory.\nBut, it's not as bad as it sounds.  TDX can be configured to never\ndeliver these exceptions on private memory with a \"TD attribute\"\ncalled ATTR_SEPT_VE_DISABLE.  The guest has no way to *set* this\nattribute, but it can check it.\nEnsure ATTR_SEPT_VE_DISABLE is set in early boot.  panic() if it\nis unset.  There is no sane way for Linux to run with this\nattribute clear so a panic() is appropriate.\nThere's small window during boot before the check where kernel\nhas an early #VE handler. But the handler is only for port I/O\nand will also panic() as soon as it sees any other #VE, such as\na one generated by a private memory access.\n[ dhansen: Rewrite changelog and rebase on new tdx_parse_tdinfo().\nAdd Kirill's tested-by because I made changes since\nhe wrote this. ]"
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2022-49886\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-49886\nhttps://lore.kernel.org/linux-cve-announce/2025050156-CVE-2022-49886-3c97@gregkh/T"
  ]
}